### PR TITLE
lazy regex

### PR DESCRIPTION
**Pull request by michalkow**
allows for many translations in single line

### CODE REVIEW

**Comment by lucastschmidt** [comment]
I will do later a quick test here and merge. I dont even remember if this has any automatic tests, its been 1year+ since I dont use this.

**Comment by lagoasoft-lucasschmidt** [comment]
Hey @michalkow , do you have an example where this change applies to? In all my cases I possibly didnt have this.

**Comment by michalkow** [comment]
Here is the example with the old regex: https://regex101.com/r/fR2iR7/2
Adding `?` solved problem for me.
I have i18n-node style translations in my React client-side code, that is why I found your repo useful :)

**Comment by lagoasoft-lucasschmidt** [comment]
Yeah, no problem @michalkow 

I use jade as html (maybe thats why I didnt encounter issues), but good that you solved the issue.

**Pull request merged**
